### ISSUE TITLE
libz-rs-sys functions are missing #[no_mangle]

### ISSUE THREAD

**Issue by glandium** [memorysafety/zlib-rs#124]
```
$ cat > foo.rs <<EOF
#[no_mangle]
pub extern "C" fn foo() {}

pub extern "C" fn bar() {}
EOF
$ rustc --crate-type lib foo.rs
$ nm libfoo.rlib
nm libfoo.rlib 

lib.rmeta:
nm: lib.rmeta: no symbols

foo.foo.a77a36e9eb12c384-cgu.0.rcgu.o:
0000000000000000 T _ZN3foo3bar17h58f86806802c8f61E
0000000000000000 T foo
```

See how the symbol for functions is mangled unless `#[no_mangle]` is applied to it.

Without `[no_mangle]`, the library cannot be used as a replacement for libz for C code.

That said, in some cases, it is also desirable to rename the symbols completely. For instance, in the Firefox code base, [this is in place](https://searchfox.org/mozilla-central/rev/b220e40ff2ee3d10ce68e07d8a8a577d5558e2a2/modules/zlib/src/mozzconf.h#16-172) to avoid unexpectedly ending up using the system libz through some other system library.

**Comment by folkertdev** [comment]
The https://github.com/memorysafety/zlib-rs/pull/125 PR will fix the problem. it turns out `no_mangle` does not work for us during tests, because we link to a C version of the library that already uses the names. So `#[export_link = "name"]` is used instead, and I add a prefix when `cfg(test)`. 

```
> objdump -tT target/debug/liblibz_rs_sys.so | grep "uncompress"
0000000000080da8 l     O .got	0000000000000000              _ZN7zlib_rs7inflate10uncompress17he7d985e55c58a189E$got
000000000002c2f0 l     F .text	00000000000001ef              _ZN7zlib_rs7inflate10uncompress17he7d985e55c58a189E
00000000000240b0 g     F .text	000000000000008e              uncompress
00000000000240b0 g    DF .text	000000000000008e  Base        uncompress
```

I think we could extend that mechanism to allow for custom prefixes. Would this solution work: we add a `custom-prefix` feature, that when enabled, uses the prefix found in the `LIBZ_RS_SYS_PREFIX` environment variable to generate the `#[export_link = "..."]`?

**Comment by glandium** [comment]
Yes, that should work, thanks.
