### ISSUE TITLE
Please provide a separate crate for the cdylib

### ISSUE THREAD

**Issue by glandium** [memorysafety/zlib-rs#166]
Cargo is great and all, but in many cases, it's also annoying. Crates with multiple crate-types is one such cases. When you have a crate that depends on a crate with multiple crate-types, all the crate types are compiled, even though, being a dependency, only the rlib is needed, and cargo can't/won't do anything with the other types.

In the Firefox case, this causes build issues because it tries to link the cdylib, and in some cases (sanitizer, cross-compilation) it makes things harder than they need to be.

**Comment by folkertdev** [comment]
so if I'm understanding you correctly, you are using `libz-rs-sys` as a rust dependency, not (directly) as a dynamic library?

anyway, does https://github.com/memorysafety/zlib-rs/pull/168 seem like it would work for you? I hadn't really considered that approach before but it turns out its kind of nice for documentation and testing to have the cdylib build be separate.

**Comment by glandium** [comment]
Yes, and yes.

**Comment by folkertdev** [comment]
fixed by https://github.com/memorysafety/zlib-rs/pull/168
